#!/bin/sh
#
# Sebastian Rockel, 2010-01-15
# Script for syncing or archiving basic repository files
#
# $1 : -s for syncing
#      -a for archiving
#
FLIST=files.txt # List of files in repository
HOSTTARGET="demo@tams67:projekt090406/"
#HOSTTARGET="8rockel@tams50:projekt090406/"
TMPDIR="PlayerSource"
ARCHFILE=$TMPDIR".tgz"

if [ -z $1 ] ; then
  echo
  echo "`basename $0` [ -s | -a ]"
  echo "-s : sync to $HOSTTARGET"
  echo "-a : archive to $ARCHFILE"
  echo
  exit 0
fi

# Syncing
if [ $1 = "-s" ] ; then
  for  file in `cat $FLIST | sed -e 's/#.*//'` ; do
    scp -r $file $HOSTTARGET || exit -1
  done
  echo ; echo "Copied files to $HOSTTARGET" ; echo
# Archiving
elif [ $1 = "-a" ] ; then
  mkdir $TMPDIR || exit -1
  for  file in `cat $FLIST | sed -e 's/#.*//'` ; do
    cp -fr $file $TMPDIR || exit -1
  done
  tar -czvf $ARCHFILE $TMPDIR/* || exit -1
  rm -fr $TMPDIR || exit -1
  echo ; echo "Created archive $ARCHFILE" ; echo
# Unknown
else
  echo ; echo "Invalid argument: $1" ; echo
  exit -1
fi

exit 0
