#!/bin/sh
# Create doxygen directory and doxyfy
doxyhtmldir="./doc/doxygen/html/"

if [ ! -d doc/doxygen/html ]; then
  mkdir $doxyhtmldir
fi
cp tools/PioneerShape.png doc/doxygen/html/
cp tools/AngleDefinition.png doc/doxygen/html/
doxygen

