#!/bin/sh
# Start player server an program on real pioneer
prefix="stage_local"
world="pioneer"

player $prefix/$world.cfg & # Stage world
sleep 2 # Wait for Stage world to come up
if [ -z $# ] ; then
  ./$1
else
  ./wallfollow
fi
