#!/bin/sh
prefix="stage_local"
world="uhh"
pport=6665 # Player port

player -p $pport $prefix/$world.cfg & # Stage world
sleep 2 # Wait for Stage world to come up
if [ -z $# ] ; then
  ./$1
else
  ./wallfollow
fi
