# Makefile
# Starts a stage world for localization and navigation

.PHONY: tams pnav all uhh

all: 
	@echo
	@echo "make pnav \t-- Starts a simple navigation example"
	@echo "make tams \t-- Starts the TAMS floor nav example"
	@echo "make uhh  \t-- Starts the UHH floor nav example"
	@echo

pnav:
	./stage pnav

tams:
	./stage tams

uhh:
	./stage uhh
