#!/bin/sh
DefCSWait=10 # Seconds to wait default for c-space generation
TamsCSWait=80 # Seconds to wait for tams c-space generation
DefStageWait=2 # Seconds to wait for Stage world to come up

world=${1}  # Get Stage world as parameter

if [ $world == "tams" ] ; then
  CSWait=$TamsCSWait
else
  CSWait=$DefCSWait
fi
echo "Playernav start delayed $CSWait seconds to wait for C-Space generation."

player ${world}_stage.cfg & # Start Stage world

sleep $DefStageWait # Wait for Stage world to come up
#player -q writelog.cfg & # Start writelog driver
player -q ${world}_navloc.cfg & # Localization and Path planning

sleep $CSWait # Wait for Wavefront driver's C-Space creation
playernav # Run playernav on a remote machine

killall player # Kill player processes in background
